[project]
name = "sra_metadata"
version = "0.1.0"
description = "Add a short description here"
authors = ["Luiz Irber <contact+github@luizirber.org>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "linux-aarch64"]

[tasks]
download = "mkdir -p inputs && aws s3 cp --recursive s3://sra-pub-metadata-us-east-1/sra/metadata/ inputs/ --no-sign-request"
subset = "cat query.sql | duckdb"

[dependencies]
duckdb = ">=1.0.0,<2"
awscli = ">=2.17.18,<3"
