[project]
name = "sra_metadata"
version = "0.1.0"
description = "Add a short description here"
authors = ["Luiz Irber <contact+github@luizirber.org>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "linux-aarch64"]

[tasks]
install_parquet = "echo 'INSTALL parquet;' | duckdb"
download = "mkdir -p inputs && aws s3 cp --recursive s3://sra-pub-metadata-us-east-1/sra/metadata/ inputs/ --no-sign-request"
subset = "cat subset.sql | duckdb"
load = "cat load.sql| duckdb metadata.db"

[dependencies]
duckdb-cli = ">=1.0.0,<2"
awscli = ">=2.17.18,<3"
python-duckdb = ">=1.0.0,<2"

[system-requirements]
linux = "3.10"
libc = "2.17"
macos = "12.0"
